[workspace]

members = [
	"token",
	"lexer",
	"ast",
	"parser",
	"object",
	"sema",
	"eval",
	"code",
	"compiler",
	"vm",
	"repl",
]

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
debug = true
panic = "abort"

