[workspace]

members = [
	"utils",
	"token",
	"lexer",
	"ast",
	"parser",
	"object",
	"sema",
	"eval",
	"code",
	"compiler",
	"vm",
	"repl",
]

[profile.release]
lto = "fat"
debug=true
opt-level = 3
panic = "abort"

